name: Entur/Slack/CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update-post-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1.0.0
    with:
      workflow_file: .github/workflows/post.yml
      readme_file: README-post.md

  post-message:
    uses: ./.github/workflows/post.yml
    with:
      channel: "GFBL95A0J" # notify-plattform
      team: plattform
      release_name: gha-slack
    secrets: inherit
