name: Entur/Slack/CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify-pr:
    name: Verify PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: entur/gha-meta/.github/workflows/verify-pr.yml@v1

  update-post-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1.0.0
    with:
      workflow_file: .github/workflows/post.yml
      readme_file: README-post.md

  test-post-message:
    uses: ./.github/workflows/post.yml
    with:
      channel_id: "C01AVRY6Q23" # notify-plattform
      message: "gha-slack CI: Test to send simple plain text message\n with line break using gha-slack/post!"
    secrets: inherit

  test-post-message-with-blocks:
    uses: ./.github/workflows/post.yml
    with:
      channel_id: "C01AVRY6Q23" # notify-plattform
      blocks: |
        {
         	"blocks": [
        		{
         			"type": "section",
         			"text": {
          				"type": "mrkdwn",
          				"text": "*gha-slack CI: Test to send JSON rich message using Block Kit from gha-slack/post!!* :rocket:"
             	}
            },
            {
         			"type": "divider"
            },
            {
         			"type": "section",
         			"fields": [
        				{
         					"type": "mrkdwn",
         					"text": "*Repository:*\n<https://github.com/entur/gha-slack|gha-slack>"
        				},
        				{
         					"type": "mrkdwn",
         					"text": "*Workflow:*\n<https://github.com/entur/gha-slack/.github/workflows/post.yml|post>"
        				}
         			]
            }
         	]
        }
    secrets: inherit
