name: Entur/Slack/Post

on:
  workflow_call:
    inputs:
      channel:
        description: "Slack channel to post the message"
        type: string
        required: true
      blocks:
        description: "The Slack blocks to include in the message (as a JSON string)"
        required: false
        type: string
      message:
        description: "Fallback message to post to Slack (required if blocks are not provided)"
        type: string
        required: false
      timeout_minutes:
        description: "Job timeout in minutes"
        type: number
        default: 5
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_SLACK_POST_CHANNEL=${{ inputs.channel }}" >> $GITHUB_ENV
      - if: env.GHA_SLACK_POST_BLOCKS != ''
        id: slack-post-block
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ env.GHA_SLACK_POST_CHANNEL }}
          payload: |
            ${{ inputs.blocks }}
      - id: slack-post-message
        if: env.GHA_SLACK_POST_BLOCKS == ''
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ env.GHA_SLACK_POST_CHANNEL }}
          slack-message: ${{ inputs.message }}
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
