name: Entur/Slack/Post

on:
  workflow_call:
    inputs:
      channel:
        description: "Slack channel"
        type: string
        required: true
      team:
        description: "Team name"
        type: string
        required: true
      release_name:
        description: "Release name, default $repo_name"
        type: string
        default: "repo_name"
      image:
        description: "Image name"
        type: string
        default: "N/A"
      mode:
        description: "What kind of event triggered the message"
        type: string
        default: "CD"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 40
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_SLACK_POST_CHANNEL=${{ inputs.channel }}" >> $GITHUB_ENV
          echo "GHA_SLACK_POST_TEAM=${{ inputs.team }}" >> $GITHUB_ENV
          echo "GHA_SLACK_POST_RELEASE_NAME=${{ inputs.release_name }}" >> $GITHUB_ENV
          echo "GHA_SLACK_POST_IMAGE=${{ inputs.image }}" >> $GITHUB_ENV
          echo "GHA_SLACK_POST_MODE=${{ inputs.mode }}" >> $GITHUB_ENV
      - id: set-release-name
        shell: bash
        run: |
          if [[ "${{ env.GHA_SLACK_POST_RELEASE_NAME }}" = "repo_name" ]]; then
            echo "GHA_SLACK_POST_RELEASE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          fi
      - id: set-message
        shell: bash
        run: |
          echo "GHA_SLACK_POST_MESSAGE=*${{ env.GHA_SLACK_POST_TEAM }}* / _${{ github.actor }} (${{ env.GHA_SLACK_POST_MODE }})_\n*${{ env.GHA_SLACK_POST_RELEASE_NAME }}*\n`${{ env.GHA_SLACK_POST_IMAGE }}`" >> $GITHUB_ENV
      - id: slack-push
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ env.GHA_SLACK_POST_CHANNEL }}
          payload: |
            {
              "text": "${{ env.GHA_SLACK_POST_MESSAGE }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.GHA_SLACK_POST_MESSAGE }}"
                  }
                }
              ]
            }
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
