name: Entur/Slack/Post

on:
  workflow_call:
    inputs:
      channel_id:
        description: "Slack channel id you wish to post message to"
        type: string
        required: true
      blocks:
        description: "The Slack blocks to include in the message (as a JSON string)"
        required: false
        type: string
      message:
        description: "Simple plain text message to post to Slack"
        required: false
        type: string
      timeout_minutes:
        description: "Job timeout in minutes"
        type: number
        default: 5
jobs:
  slack-post:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
    steps:
      - id: set-env
        shell: bash
        # Blocks are passed as a JSON string, so we need to wrap them in a heredoc using single quotes sice the JSON string may contain double quotes
        run: |
          echo "GHA_SLACK_POST_CHANNEL=${{ inputs.channel_id }}" >> $GITHUB_ENV
          echo "GHA_SLACK_POST_MESSAGE<<EOM" >> $GITHUB_ENV
          echo "${{ inputs.message }}" >> $GITHUB_ENV
          echo "EOM" >> $GITHUB_ENV
          echo 'GHA_SLACK_POST_BLOCKS<<EOB' >> $GITHUB_ENV
          echo '${{ inputs.blocks }}' >> $GITHUB_ENV
          echo 'EOB' >> $GITHUB_ENV
      - if: env.GHA_SLACK_POST_MESSAGE != ''
        id: slack-post-message
        uses: slackapi/slack-github-action@v2.0.0
        with:
          channel-id: ${{ env.GHA_SLACK_POST_CHANNEL }}
          slack-message: ${{ env.GHA_SLACK_POST_MESSAGE }}
      - if: env.GHA_SLACK_POST_BLOCKS != ''
        id: slack-post-block
        uses: slackapi/slack-github-action@v2.0.0
        with:
          channel-id: ${{ env.GHA_SLACK_POST_CHANNEL }}
          payload: |
            ${{ env.GHA_SLACK_POST_BLOCKS }}
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
